### ISSUE TITLE
Support for Python 3?

### ISSUE THREAD

**Issue by mbadran** [theY4Kman/python-pocketsmith-api#2]
Hi there,

This is very cool, thanks for putting it out! 

Is there any chance you can publish this on pip with support for Python 3?

**Comment by theY4Kman** [comment]
OH! I guess I didn't mark the project as 2.7+ — I labeled it `^2.7`, which actually means `>=2.7, <3.0` :P Lemme fix this up, too

**Comment by theY4Kman** [comment]
Okay, I dropped support for Python 2.7 (now it's 3.6+ only), and published v1.0.0 to PyPI :)

**Comment by theY4Kman** [comment]
Also, just FYI: there were a handful of things I needed when building my own personal finance dashboard — like searching transactions, manually syncing institutions, and automatically providing MFA info for some of my banks, so I could set them to auto-sync — which the API just doesn't have any support for. 

To remedy that, I wrote a web client capable of filling some of the holes in the API. I just open-sourced it. Maybe it's useful to ya: https://github.com/theY4Kman/python-pocketsmith-web-client
